# Generated by Django 5.2.3 on 2025-06-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='depertment',
            field=models.CharField(default='CST', max_length=100),
        ),
    ]
